language: python
matrix:
  include:
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38
  - python: 3.9
    env: TOXENV=py39
  - python: 3.7
    env: TOXENV=py3pep8
  - python: 3.7
    env: TOXENV=docs
before_install:
- pip install codecov tox
script:
- tox
after_success:
- codecov -e TOXENV
deploy:
  provider: pypi
  username: __token__
  password:
    secure: IRXJm9yeE+MKVA+rVkcET8DC7AQf1I3UCs4x34de/Wm2LAkRwt6mv3Fso+vAYivf+QPUR/GTtGucoBIrENxioUu61gYa45C9i9G7bQjtUmVxDnPyapzCTADXc2QG//9m/imx1iySq1xXayGDAsHMo7Ox5MrdF0HpSksFrw+copHy170T4eNiWSvFCUCG3EXDoijTC8PpIbL05xSujV+ZumHFuIxUrYLdwms+HMNEqzCrHQpASN85FBZAxXeJ267uFSSe6VBbO+FtAa5k3/dYygyIwC3qDbCEJwVPNJug6PTJNylHjtKwTirxQsX/dkytIIxbKCmw/C+BcsF871KktrvYlMFKznQ4hNbfnM3XCs2xCQRx80LVAX+pGRqUBXuwlzCzLxO2pP+jDrdVdONTPFUJfzdVtwgOURXhIv2kX8Wk3ZV/pjLTitYf4YAmH97gW9U5rcvWHxPsvP/pOvzrSlGYcVI8ybJtYsZzE3qlGFikmFQWx/7/NLi3cK04UAM5CLfYcyiJxOl7nMhe5DlJOC6/0prdjM1wwwMkq3cx4rad6HvZLx4cE9F//MDglKCCLIe1kg4znQJsb4hjyGRk7y1+AxFlZb/i2IYrJljFSYtC/ZipQ7y+hq1o+SCi+l+H9Dx1jQWKOFoyCbOvLBJcgveO8VPO68dHUjd1zJlOLuE=
  skip_existing: true
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  true:
    condition: $TOXENV == py37
    all_branches: true
