# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38
  - python: 3.9
    env: TOXENV=py39
  - python: 3.7
    env: TOXENV=py3pep8
  - python: 3.7
    env: TOXENV=docs

before_install:
- pip install codecov tox

script:
- tox

after_success:
- codecov -e TOXENV

deploy:
  provider: pypi
  username: __token__
  password:
    secure: E7s6xFzYqUkU4wYTY8KKEdEGBdj9DeyHsAG07LjdD+yirGUgaBwicJ6cM7Gyrvlhr5DsKYNL4CmNJGEHBub1kyGqN77JowBIIF6wrtD7t/hmGcDvVdGcXxOasoFYWJFfdceLCq2x7wGmaE3Sqb375ww+VAMdBRldDyvS468nDclGmvtMI5BD//Q8ASRnqtI0uj3vHY43z+wbr/l1zV1XVeSgcdJSVxYmJLFodD6spiNvBhsrQYntEdNwo09soLuKM8Fu8MfQ7et4mdl+kHJN3kdL/FKdSW09d6ScumenUFij9mXwyOjtQijnk0L5FT6+HfcpeN3Lol+XjEPaYoCDOw9lMrACsrWbQs2LXpHxCGYDdr+h+oSGXOXl8M9/52LfOWLcmvFrUJUsI6DsZm0yC+o4HgSSgCpWxnbc6gzPiBKbSYzr70inh7DuOEZRvH/McH11o+/c6CPWhct38Pf+8zlf+pvabjVNUfR5cX9jVu/k+yATkqIqjHK/IRoSEekYy/kOWnbwARew8jz6G3h+jXt/hGuC2LfWEAEUipcdts3+Oxl+Ps8dNFm3AWLsrl5c/NR0YrqO3KiklnfVjmn+zrn/whpF4MtpPCwONYDPCj79hzFOYHFOdqRl9pHlypE9qlXak7WaXiTry6/l+W/gN5C46VgvBOqN+SfFrNA86J8=
  skip_existing: true
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  on:
    condition: $TOXENV == py37
    all_branches: true
    tags: true
