language: python
matrix:
  include:
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38
  - python: 3.9
    env: TOXENV=py39
  - python: 3.7
    env: TOXENV=py3pep8
  - python: 3.7
    env: TOXENV=docs
before_install:
- pip install codecov tox
script:
- tox
after_success:
- codecov -e TOXENV
deploy:
  provider: pypi
  username: __token__
  password:
    secure: BeWPjSUVjdeehInODnBz0IXM06E41GMyHKU35X/ZnYCbdTNihDu8wa9h8fPgZmV8ATh3MiytdejYufgqvjel1x5xG8+s7Lc7gFfltO7SK1eYI0oH0H1+lKskAOLrh2gzR4N+iJZ+2kPlYBRZfiPhJ/JXFKsnn5IxbKIdP/aWiyNTPrtXSVESRMy5wLb9R4hiGDuQhhkfGJxhqhry98s6ZuRdCKW6We4EyyYYhqafBOYQ+jWGiUU6yYiwVsrJ+682fnKFg26U05e2+pYDJBZU3IUPKKcg8MVApx+3G25JLmgbh972JQb/Di2EM+v+zBzSgJikG67k3Kej40C1reoUQHjBRHmR7UWw4BvdVmGAJtDg9u/wLVE9yvZcDxEbSwVqz5M1Z7fnNP/FbBjXKgNtv94WRII9rP/uxXZy/rp6GX3+lrDkHy67Z3FXOUUZbDGeTplaskihyHeR8X2HKKTXQDvaAuyKXfgAsoBeAGZO0MFBrLevUVA99XfEwRT5S1jmqBVlb6VC1oiYsSvvH0huAviHfSeBZVQkI1yPiDIs0Qcwh8Jy4mmwD1XF1G/19i16T75p4el+pleomzNy4AvBrcJfsO+BJU6F+XK7ObuB0iHkFcnUIRs6zO76WK/aqf8xqgJn8SW8b5VUu0cEl0LLePFOkfV72WYBdlKFiPd8vWk=
  skip_existing: true
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  true:
    condition: $TOXENV == py37
    all_branches: true
